config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }

  resources :users, only: [:show]
    namespace :admin do
      resources :users, only: [:index, :destroy]
    end

  resources :posts, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get 'detail'
    end
  end

  resources :messages, only: [:index, :show, :create]
  resources :bulletins, only: [:index, :create, :destroy]
  resources :newsletters, only: [:index, :create, :destroy]

  root 'home#index'

  authenticate :user, -> (u) {u.admin?} do
    mount Sidekiq::Web, at: '/sidekiq'
  end
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id         :bigint           not null, primary key
#  content    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  room_id    :integer
#  user_id    :integer
#
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  validates :user_id, :room_id, presence: true
  validates :content, presence: true, length: { maximum: 250 }
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @user = current_user
    @others = User.where.not(id: current_user.id)
  end

  def show
    @user = current_user
    @other = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @other.id, room_id: rooms)

    if user_rooms.nil?
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @other.id, room_id: @room.id)
    else
      @room = user_rooms.room
    end

    @messages = @room.messages.includes(:user)
    @message = Message.new(room_id: @room.id)
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to request.referer
    end
  end

  private

  def message_params
    params.require(:message).permit(:content, :room_id).merge(user_id: current_user.id)
  end
end

app/views/messages/index.html.erb
<% provide(:title, "トークルーム") %>
<div class="form-signin">
  <h1 class="ff-so">Talk Room</h1>
  <h6>トーク相手を選んでください</h6>
  <% if current_user != @others %>
    <% @others.each do |other| %>
      <div class="row border-bottom pt-3">
        <%= link_to message_path(other.id), class:"plain" do %>
          <div class="d-flex justify-content-center align-items-center">
            <div class="px-2">
              <% if other.picture.attached? %>
                <%= image_tag other.picture.variant( resize: "75x75^", gravity: "center", crop: "75x75+0+0" ).processed, class: "rounded-circle" %>
              <% else %>
                <%= image_tag 'default_user_icon.png', class: "rounded-circle", style: "width: 75px; height: 75px;" %>
              <% end %>
            </div>
            <div class="px-2 fs-3">
              <%= other.name %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <div class="active text-center my-4">
    <%= button_to "Back", root_path, method: :get, class: "btn btn-outline-danger btn-lg fw-bold mx-3" %>
  </div>
</div>

app/views/messages/show.html.erb
<% provide(:title, "トークルーム") %>
<div class="container clearfix">
  <div class="row">
    <div class="col-xs-6">
        <table class="table">
          <thead>
            <tr>
              <th class="text-start fs-2"><%= @other.name %></th>
              <th class="text-end fs-2"><%= current_user.name %></th>
            </tr>
          </thead>
          <% @messages.each do |message| %>
            <% if message.user_id == current_user.id %>
            <tbody>
              <tr>
                <th></th>
                <th class="message-box-blue">
                  <p class="text-end"><%= message.content %></p>
                </th>
              </tr>
            <% else %>
              <tr>
                <th class="message-box-grey">
                  <p class="text-start"><%= message.content %></p>
                </th>
                <th></th>
              </tr>
            </tbody>
            <% end %>
          <% end %>
        </table>

        <%= form_with model: @message, class:"text-end pt-3", remote: true do |f| %>
          <%= f.text_field :content %>
          <%= f.hidden_field :room_id %>
          <%= f.button :type => "submit", class:"btn btn-sm btn-primary" do %>
            <span class="material-icons align-bottom">send</span>
          <% end %>
        <% end %>
    </div>
    <div class="active text-center my-3">
      <%= button_to "Back", messages_path, method: :get, class: "btn btn-outline-danger btn-lg fw-bold mx-3" %>
    </div>
  </div>
</div>