config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }

  resources :users, only: [:show]
    namespace :admin do
      resources :users, only: [:index, :destroy]
    end

  resources :posts, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get 'detail'
    end
  end

  resources :messages, only: [:index, :show, :create]
  resources :bulletins, only: [:index, :create, :destroy]
  resources :newsletters, only: [:index, :create, :destroy]

  root 'home#index'

  authenticate :user, -> (u) {u.admin?} do
    mount Sidekiq::Web, at: '/sidekiq'
  end
end

app/models/newsletter.rb
# == Schema Information
#
# Table name: newsletters
#
#  id         :bigint           not null, primary key
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#
class Newsletter < ApplicationRecord
  belongs_to :user
  has_one_attached :letter
end

app/controllers/newsletters_controller.rb
class NewslettersController < ApplicationController
  before_action :admin_user, only: [:destroy]

  def index
    @user = current_user
    @newsletters = Newsletter.order('created_at desc')
  end

  def create
    @user = current_user
    @newsletter = Newsletter.new(newsletter_params)
    if @newsletter.save
      flash[:notice] = "アップロードできました。"
      redirect_to newsletters_path
    else
      @newsletters = Newsletter.all
      flash[:alert] = "アップロードできませんでした。"
      render("newsletters/index")
    end
  end

  def destroy
    Newsletter.find(params[:id]).destroy
    flash[:success] = "ファイルを削除しました。"
    redirect_to newsletters_path
  end

  private

  def newsletter_params
    params.permit(:title, :letter).merge(user_id: current_user.id)
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/views/newsletters/index.html.erb
<% provide(:title, "園だより") %>
<div class="container clearfix">
  <h1 class="ff-so text-center">Newsletter</h1>
  <div class="row">
    <div class="col-12">
      <div class="form-signin">
        <% if @user.admin? %>
          <%= form_with url: "/newsletters", method: :post, local: true do |f| %>
            <div class="active text-center my-3">
              <%= f.text_field :title, class: "form-control", placeholder: "タイトル" %>
              <%= f.file_field :letter, class: "my-3" %>
              <%= f.submit "アップロード", class: "btn btn-primary btn-lg fw-bold mx-3" %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="row px-3">
        <% @newsletters.each do |f| %>
          <table class="table-border-bottom mb-3">
            <tbody>
              <tr>
                <td class="border-none pb-0"><%= f.created_at&.strftime("%-m月%-d日(#{%w(日 月 火 水 木 金 土)[f.created_at.wday]})") %></td>
              </tr>
              <tr>
                <td class="border-none text-secondary">
                  <%= link_to rails_blob_path(f.letter.attachment) do %>
                    <p class="fs-5"><%= f.title %><span class="material-icons align-bottom">file_download</span></p>
                  <% end %>
                </td>
              </tr>
              <% if current_user.admin? %>
              <tr>
                <td class="border-none text-secondary">
                  <%= button_to "ファイル削除", newsletter_path(f), method: :delete %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
        <div class="active text-center my-3">
          <%= button_to "Back", root_path, method: :get, class: "btn btn-outline-danger btn-lg fw-bold mx-3" %>
        </div>
      </div>
    </div>
  </div>
</div>