config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }

  resources :users, only: [:show]
    namespace :admin do
      resources :users, only: [:index, :destroy]
    end

  resources :posts, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get 'detail'
    end
  end

  resources :messages, only: [:index, :show, :create]
  resources :bulletins, only: [:index, :create, :destroy]
  resources :newsletters, only: [:index, :create, :destroy]

  root 'home#index'

  authenticate :user, -> (u) {u.admin?} do
    mount Sidekiq::Web, at: '/sidekiq'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.find_by(id: current_user.id)
  end
end

app/views/home/_card.html.erb
<div class="card bgc-none p-2">
  <% if @user.picture.attached? %>
    <%= image_tag @user.picture.variant( resize: "300x300^", gravity: "center", crop: "300x300+0+0" ).processed, class: "card-img-top mx-auto rounded-circle" %>
  <% else %>
    <%= image_tag 'default_user_icon.png', class: "card-img-top mx-auto rounded-circle" %>
  <% end %>
  <div class="card-body d-none d-md-block">
    <h4 class="card-title ff-so"><%= "#{@user.name}" %></h4>
    <% if !@user.admin? %>
      <p class="card-text">
        <span class="text-secondary border-bottom"><%= "#{@user.dob&.strftime("%Y年%m月%d日")}" %></span><br>
        <span class="text-secondary border-bottom"><%= "#{@user.sex}" %></span><br>
        <span class="text-secondary border-bottom"><%= "#{@user.bloodtype}" %></span>
      </p>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<% provide(:title, "HOME") %>
<div class="container clearfix">
  <div class="row">
    <div class="col-md-3 col-12">
      <%= render partial: "card" %>
    </div>
    <div class="col-md-9 col-12">
      <div class="row h-100 text-center align-items-center mt-3 mb-4">
        <div class="col-6">
          <%= link_to posts_path, class: "plain" do %>
            <span class="material-icons md-60 grey">description</span><br>
            <h5>連絡帳</h5>
          <% end %>
        </div>
        <div class="col-6">
          <%= link_to bulletins_path, class: "plain" do %>
            <span class="material-icons md-60 yellow">lightbulb</span><br>
            <h5>お知らせ</h5>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-3 col-12 d-none d-md-block">
    </div>
    <div class="col-md-9 col-12">
      <div class="row h-100 text-center align-items-center mt-3 mb-4">
        <div class="col-6">
          <%= link_to messages_path, class: "plain" do %>
            <span class="material-icons md-60 green">chat</span><br>
            <h5>トークルーム</h5>
          <% end %>
        </div>
        <div class="col-6">
          <%= link_to newsletters_path, class: "plain" do %>
            <span class="material-icons md-60 pink">local_post_office</span><br>
            <h5>園だより</h5>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>