config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }

  resources :users, only: [:show]
    namespace :admin do
      resources :users, only: [:index, :destroy]
    end

  resources :posts, only: [:index, :show, :create, :edit, :update, :destroy] do
    member do
      get 'detail'
    end
  end

  resources :messages, only: [:index, :show, :create]
  resources :bulletins, only: [:index, :create, :destroy]
  resources :newsletters, only: [:index, :create, :destroy]

  root 'home#index'

  authenticate :user, -> (u) {u.admin?} do
    mount Sidekiq::Web, at: '/sidekiq'
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id            :bigint           not null, primary key
#  bathroom      :string(255)
#  bathroom_time :datetime
#  comment       :text(65535)
#  date          :date
#  pick_up       :string(255)
#  pick_up_time  :datetime
#  sleep         :datetime
#  temperature   :float(24)
#  wake_up       :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  box_id        :integer
#  user_id       :integer
#
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :box
  validates :user_id, :box_id, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_current_user

  def index
    @others = User.where.not(id: current_user.id)
    @admin = User.where(:admin => true)
  end

  def new
    @post = Post.new
  end

  def show
    @other = User.find(params[:id])
    boxes = current_user.user_boxes.pluck(:box_id)
    user_boxes = UserBox.find_by(user_id: @other.id, box_id: boxes)

    if user_boxes.nil?
      @box = Box.new
      @box.save
      UserBox.create(user_id: current_user.id, box_id: @box.id)
      UserBox.create(user_id: @other.id, box_id: @box.id)
    else
      @box = user_boxes.box
    end

    @posts = @box.posts.includes(:user).order('created_at desc')
    @post = Post.new(box_id: @box.id)
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "登録しました。"
      redirect_to request.referer
    end
  end

  def detail
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.save
      flash[:notice] = "更新しました。"
      redirect_to posts_path
    else
      flash[:alert] = "更新できませんでした。"
      render("post/edit")
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "ファイルを削除しました。"
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:wake_up, :bathroom, :bathroom_time, :sleep, :pick_up, :pick_up_time,
                                 :date, :comment, :temperature, :box_id).merge(user_id: current_user.id)
  end

  def set_current_user
    @user = current_user
  end
end

app/views/posts/_card.html.erb
<div class="card bgc-none p-2">
  <% if @other.picture.attached? %>
    <%= image_tag @other.picture.variant( resize: "300x300^", gravity: "center", crop: "300x300+0+0" ).processed, class: "card-img-top mx-auto rounded-circle" %>
  <% else %>
    <%= image_tag 'default_user_icon.png', class: "card-img-top mx-auto rounded-circle" %>
  <% end %>
  <div class="card-body d-none d-md-block">
    <h4 class="card-title ff-so"><%= "#{@other.name}" %></h4>
    <p class="card-text">
      <span class="text-secondary border-bottom"><%= "#{@other.dob&.strftime("%Y年%m月%d日")}" %></span><br>
      <span class="text-secondary border-bottom"><%= "#{@other.sex}" %></span><br>
      <span class="text-secondary border-bottom"><%= "#{@other.bloodtype}" %></span>
    </p>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f| %>
  <table>
    <tbody>
      <tr>
        <td class="td-color1" scope="row">前夜</td>
        <td class="td-color2 width30""><span class="material-icons align-bottom">bedtime</span>就寝</td>
        <td class="td-color2"><%= f.time_field :sleep %></td>
      </tr>
      <tr>
        <td class="td-color3" rowspan="4" scope="row">今朝</td>
        <td class="td-color4 width30""><span class="material-icons align-bottom">sunny</span>起床</td>
        <td class="td-color4"><%= f.time_field :wake_up %></td>
      </tr>
      <tr>
        <td class="td-color4 width30""><span class="material-icons align-bottom">thermostat</span>体温</td>
        <td class="td-color4"><%= f.number_field :temperature, in: 35.0..42.0, step: 0.1 %>℃</td>
      </tr>
      <tr>
        <td class="td-color4 width30""><span class="material-icons align-bottom">emoji_people</span>お迎え</td>
        <td class="td-color4"><%= f.select :pick_up, ["お父さん", "お母さん", "お祖父さん", "お祖母さん", "兄弟"], { include_blank: true }, { id: "pick_up"} %></td>
      </tr>
      <tr>
        <td class="td-color4 width30""><span class="material-icons align-bottom">schedule</span>迎え時間</td>
        <td class="td-color4"><%= f.time_field :pick_up_time %></td>
      </tr>
      <tr>
        <td class="td-color5" rowspan="2" scope="row">その他</td>
        <td class="td-color6 width30"><span class="material-icons align-bottom">wc</span>排泄</td>
        <td class="td-color6">
          <%= f.select :bathroom, ["おしっこ", "うんち（普通）", "うんち（軟便）", "うんち（コロコロ）", "うんち（水様）"], { include_blank: true }, { id: "bathroom", class: "mb-2" } %><br/>
          <%= f.time_field :bathroom_time %>
          </td>
      </tr>
      <tr>
        <td class="td-color6"><span class="material-icons align-bottom">comment</span>コメント</td>
        <td class="td-color6"><%= f.text_area :comment, class: "form-control" %></td>
      </tr>
    </tbody>
  </table>
  <div class="active text-center my-4">
    <%= f.hidden_field :box_id %>
    <%= f.submit "登録", class: "btn btn-lg btn-primary fw-bold w-25" %>
  </div>
<% end %>

app/views/posts/_user_select.html.erb
<% @admin.each do |admin| %>
  <div class="row border-bottom pt-3">
    <%= link_to post_path(admin.id), class:"plain" do %>
      <div class="d-flex justify-content-center align-items-center">
        <div class="px-2">
          <% if admin.picture.attached? %>
            <%= image_tag admin.picture.variant( resize: "75x75^", gravity: "center", crop: "75x75+0+0" ).processed, class: "rounded-circle" %>
          <% else %>
            <%= image_tag 'default_user_icon.png', class: "rounded-circle", style: "width: 75px; height: 75px;" %>
          <% end %>
        </div>
        <div class="px-2 fs-3">
          <%= admin.name %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/_user_select_admin.html.erb
<% @others.each do |other| %>
  <div class="row border-bottom pt-3">
    <%= link_to post_path(other.id), class:"plain" do %>
      <div class="d-flex justify-content-center align-items-center">
        <div class="px-2">
          <% if other.picture.attached? %>
            <%= image_tag other.picture.variant( resize: "75x75^", gravity: "center", crop: "75x75+0+0" ).processed, class: "rounded-circle" %>
          <% else %>
            <%= image_tag 'default_user_icon.png', class: "rounded-circle", style: "width: 75px; height: 75px;" %>
          <% end %>
        </div>
        <div class="px-2 fs-3">
          <%= other.name %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/posts/detail.html.erb
<% provide(:title, "連絡帳") %>
<div class="container clearfix">
  <h4><%= @post.created_at&.strftime("%-m月%-d日(#{%w(日 月 火 水 木 金 土)[@post.created_at.wday]})") %></h4>
  <table>
    <tbody>
      <tr>
        <td class="td-color1" scope="row">前夜</td>
        <td class="td-color2 width30""><span class="material-icons md-18">bedtime</span>就寝</td>
        <td class="td-color2"><%= @post.sleep&.strftime('%-H:%M') %></td>
      </tr>
      <tr>
        <td class="td-color3" rowspan="4" scope="row">今朝</td>
        <td class="td-color4 width30""><span class="material-icons md-18">sunny</span>起床</td>
        <td class="td-color4"><%= @post.wake_up&.strftime('%-H:%M') %></td>
      </tr>
      <tr>
        <td class="td-color4 width30""><span class="material-icons md-18">thermostat</span>体温</td>
        <td class="td-color4"><%= @post.temperature.to_f %>℃</td>
      </tr>
      <tr>
        <td class="td-color4 width30""><span class="material-icons md-18">emoji_people</span>お迎え</td>
        <td class="td-color4"><%= @post.pick_up %></td>
      </tr>
      <tr>
        <td class="td-color4 width30""><span class="material-icons md-18">schedule</span>迎え時間</td>
        <td class="td-color4"><%= @post.pick_up_time&.strftime('%-H:%M') %></td>
      </tr>
      <tr>
        <td class="td-color5" rowspan="2" scope="row">その他</td>
        <td class="td-color6 width30"><span class="material-icons md-18">wc</span>排泄</td>
        <td class="td-color6">
          <%= @post.bathroom %><br/>
          <%= @post.bathroom_time&.strftime('%-H:%M') %>
        </td>
      </tr>
      <tr>
        <td class="td-color6"><span class="material-icons md-18">comment</span>コメント</td>
        <td class="td-color6"><%= @post.comment %></td>
      </tr>
    </tbody>
  </table>
  <% if @post.user_id == current_user.id %>
    <div class="active text-center my-4">
      <%= link_to "編集", edit_post_path, class: "btn btn-primary btn-lg fw-bold w-25" %>
    </div>
    <div class="active text-center my-4">
      <%= button_to "削除", post_path, method: :delete, class: "btn btn-outline-secondary btn-lg fw-bold w-25" %>
    </div>
  <% end %>
  <div class="active text-center my-4">
    <%= button_to "Back", posts_path, method: :get, class: "btn btn-outline-danger btn-lg fw-bold ml-3 w-25" %>
  </div>
</div>

app/views/posts/edit.html.erb
<% provide(:title, "連絡帳") %>
<div class="container clearfix">
  <%= form_with model: @post, local: true do |f| %>
    <table>
      <tbody>
        <tr>
          <td class="td-color1" scope="row">前夜</td>
          <td class="td-color2 width30""><span class="material-icons align-bottom">bedtime</span>就寝</td>
          <td class="td-color2"><%= f.time_field :sleep, value: @post.sleep&.strftime('%H:%M') %></td>
        </tr>
        <tr>
          <td class="td-color3" rowspan="4" scope="row">今朝</td>
          <td class="td-color4 width30""><span class="material-icons align-bottom">sunny</span>起床</td>
          <td class="td-color4"><%= f.time_field :wake_up, value: @post.wake_up&.strftime('%H:%M') %></td>
        </tr>
        <tr>
          <td class="td-color4 width30""><span class="material-icons align-bottom">thermostat</span>体温</td>
          <td class="td-color4"><%= f.number_field :temperature, in: 35.0..42.0, step: 0.1, value: @post.temperature.to_f %>℃</td>
        </tr>
        <tr>
          <td class="td-color4 width30""><span class="material-icons align-bottom">emoji_people</span>お迎え</td>
          <td class="td-color4"><%= f.select :pick_up, ["お父さん", "お母さん", "お祖父さん", "お祖母さん", "兄弟"], :selected=>@post.pick_up %></td>
        </tr>
        <tr>
          <td class="td-color4 width30""><span class="material-icons align-bottom">schedule</span>迎え時間</td>
          <td class="td-color4"><%= f.time_field :pick_up_time, value: @post.pick_up_time&.strftime('%H:%M') %></td>
        </tr>
        <tr>
          <td class="td-color5" rowspan="2" scope="row">その他</td>
          <td class="td-color6 width30"><span class="material-icons align-bottom">wc</span>排泄</td>
          <td class="td-color6">
            <%= f.select :bathroom, ["おしっこ", "うんち（普通）", "うんち（軟便）", "うんち（コロコロ）", "うんち（水様）"], class: "mb-2", :selected=>@post.bathroom %><br/>
            <%= f.time_field :bathroom_time, value: @post.bathroom_time&.strftime('%H:%M') %>
            </td>
        </tr>
        <tr>
          <td class="td-color6"><span class="material-icons align-bottom">comment</span>コメント</td>
          <td class="td-color6"><%= f.text_area :comment, class: "form-control", value: @post.comment %></td>
        </tr>
      </tbody>
    </table>
    <div class="active text-center my-4">
      <%= f.submit "更新", class: "btn btn-lg btn-primary fw-bold w-25" %>
    </div>
  <% end %>
    <div class="active text-center my-4">
      <%= button_to "Back", posts_path, method: :get, class: "btn btn-outline-danger btn-lg fw-bold ml-3 w-25" %>
    </div>
</div>

app/views/posts/index.html.erb
<% provide(:title, "連絡帳") %>
<div class="form-signin">
  <h1 class="fw-bold">連絡帳</h1>
  <h6>相手を選んでください</h6>
  <% if current_user != @others %>
    <% if @user.admin? %>
      <%= render partial: "user_select_admin" %>
    <% else %>
      <%= render partial: "user_select" %>
    <% end %>
  <% end %>
  <div class="active text-center my-4">
    <%= button_to "Back", root_path, method: :get, class: "btn btn-outline-danger btn-lg fw-bold mx-3" %>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "連絡帳") %>
<div class="container clearfix">
  <div class="row">
    <div class="col-md-3 col-12 d-none d-md-block">
      <% if @user.admin? %>
        <%= render partial: "card" %>
      <% else %>
        <%= render partial: "home/card" %>
      <% end %>
    </div>
    <div class="col-md-9 col-12">
      <%= render partial: "form" %>
      <div class="justify-content-center align-items-center">
        <div class="active text-center">
          <%= button_to "Back", root_path, method: :get, class: "btn btn-outline-danger btn-lg fw-bold mx-3" %>
        </div>
      </div>
      <div class="row px-3">
        <% @posts.each do |post| %>
          <%= link_to detail_post_path(post), class: "plain px-0" do %>
            <% if post.user_id == current_user.id %>
              <table class="table-border-bottom mb-3">
                <tbody>
                  <tr>
                    <td class="border-none pb-0"><%= post.created_at&.strftime("%-m月%-d日(#{%w(日 月 火 水 木 金 土)[post.created_at.wday]})") %></td>
                  </tr>
                  <tr>
                    <td class="border-none text-secondary"><%= post.comment %></td>
                  </tr>
                </tbody>
              </table>
            <% else %>
              <table class="table-border-bottom mb-3">
                <tbody>
                  <tr>
                    <div class="d-flex align-items-center px-0">
                      <div class="px-2">
                        <% if @other.picture.attached? %>
                          <%= image_tag @other.picture.variant( resize: "35x35^", gravity: "center", crop: "35x35+0+0" ).processed, class: "rounded-circle" %>
                        <% else %>
                          <%= image_tag 'default_user_icon.png', class: "rounded-circle", style: "width: 35px; height: 35px;" %>
                        <% end %>
                      </div>
                      <div class="fs-5">
                        <%= @other.name %>
                      </div>
                    </div>
                  </tr>
                  <tr>
                    <td class="border-none pt-2 pb-0"><%= post.created_at&.strftime("%-m月%-d日(#{%w(日 月 火 水 木 金 土)[post.created_at.wday]})") %></td>
                  </tr>
                  <tr>
                    <td class="border-none text-secondary"><%= post.comment %></td>
                  </tr>
                </tbody>
              </table>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>